server:
  port: ${PORT_APP:9090}
  servlet:
    context-path: /catalogo

spring:
  application:
    title: Microsservico Catalogo
    version: 1.0
  datasource:
    url: jdbc:${DB_SGDB:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:catalogo}?currentSchema=${DB_SCHEMA:challenge}
    username: ${DB_USER:catalogo}
    password: ${DB_PASSWORD:catalogo}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: pageNumber
        default-page-size: 15
        one-indexed-parameters: true
        max-page-size: 1000
      sort:
        sort-parameter: order
  batch:
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
